name: Linters and static checkers
permissions:
  contents: read
  pull-requests: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]  # Runs on all pull requests targeting main

jobs:
  lints:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4.3.0

    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5.6.0

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt .

    - name: Run style-check
      run: |
        make style-check

    - name: Run syntax-check
      run: |
        make syntax-check

    - name: Run man-check
      run: |
        make man-check
