name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]  # Runs on all pull requests targeting main

jobs:
  test-minimum-python:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4.3.0

    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5.6.0
      with:
        # This should have the lowest supported python we want to support
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt .

    - name: Run tests
      run: |
        make test

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # This should have everything but the lowest supported python we want
        # to support
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13', '3.14']

    steps:
    - name: Checkout code
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4.3.0

    - name: Set up Python
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5.6.0
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: false

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt .

    - name: Run tests
      run: |
        make test
